// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAef6LfBD06ggflXHcQuqNuhzBkwXrF7BA',
    appId: '1:355776329294:web:d492c4f88ee3d84bbb351f',
    messagingSenderId: '355776329294',
    projectId: 'testing-9488a',
    authDomain: 'testing-9488a.firebaseapp.com',
    storageBucket: 'testing-9488a.appspot.com',
    measurementId: 'G-LP6S1WMGYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlb_sq1uYJNK1owGzETl124UEqLwthJPg',
    appId: '1:355776329294:android:d8da5c28156def3cbb351f',
    messagingSenderId: '355776329294',
    projectId: 'testing-9488a',
    storageBucket: 'testing-9488a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXYQ2I2kCwIom-USSHJ-yj9EWdo1-iDeI',
    appId: '1:355776329294:ios:f0f5d60f02df3900bb351f',
    messagingSenderId: '355776329294',
    projectId: 'testing-9488a',
    storageBucket: 'testing-9488a.appspot.com',
    iosBundleId: 'com.brandbuilders.flutterfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXYQ2I2kCwIom-USSHJ-yj9EWdo1-iDeI',
    appId: '1:355776329294:ios:dd04dc5d5de1ddfcbb351f',
    messagingSenderId: '355776329294',
    projectId: 'testing-9488a',
    storageBucket: 'testing-9488a.appspot.com',
    iosBundleId: 'com.brandbuilders.flutterfirebase.RunnerTests',
  );
}
